Conditional inference trees are a statistical approach to recursive partitioning. 
The underlying theory is embedded in a well defined framework of conditional inference (permutation tests). 
Unlike most other partitioning algorithms, variable selection and best split search are seperated. 
The split criterion the variable selection for the next split are formulated in terms 
of statistical hypothesis tests. The framework covers a wide range of different scales for $Y$ and $X$, more than
mentioned in this paper.  \\
As CART trees finds application in the RandomForest - algorithm, conditional trees can also be used for a special 
implementation of a RandomForest - algorithm. This is implemented as well in the party package with the cforest function. 
